# .github/workflows/ci.yml

name: CI Pipeline

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to checkout your repository code

    - name: Set up Python
      uses: actions/setup-python@v5 # Action to set up Python environment
      with:
        python-version: '3.9' # Specify your Python version (e.g., 3.9, 3.10, 3.11)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip # Upgrade pip
        pip install -r requirements.txt      # Install project dependencies from requirements.txt
  
